[/Script/EnhancedInput.EnhancedInputUserSettings]
bEnableUserSettings=True

[/Script/Engine.InputSettings]
bUseMouseForTouch=False
bEnableMouseSmoothing=False

; Default Enhanced Input Mappings Definitions
; Context: IMC_Default (On Foot)
; Actions:
; IA_Move (Vector2D) -> W/A/S/D
; IA_Look (Vector2D) -> Mouse XY
; IA_Sprint (Digital) -> Left Shift
; IA_Jump (Digital) -> Space Bar
; IA_Crouch (Digital) -> Left Ctrl
; IA_Interact (Digital) -> E
; IA_EnterExitVehicle (Digital) -> F
; IA_Aim (Digital) -> Right Mouse Button
; IA_Attack (Digital) -> Left Mouse Button
; IA_Reload (Digital) -> R
; IA_Smartphone (Digital) -> Tab
; IA_Map (Digital) -> M
; IA_Pause (Digital) -> Escape
; IA_Cover (Digital) -> Q
; IA_Dodge (Digital) -> Left Alt / Double Tap Direction

; Context: IMC_Vehicle (In Vehicle)
; Actions:
; IA_ThrottleSteer (Vector2D) -> W/S (Throttle/Brake), A/D (Steering)
; IA_Handbrake (Digital) -> Space Bar
; IA_Horn (Digital) -> H
; IA_Siren (Digital) -> Q
; IA_Headlights (Digital) -> L
; IA_RadioToggle (Digital) -> R
; IA_Seatbelt (Digital) -> B
; IA_Nitro (Digital) -> Left Shift
; IA_ChangeCamera (Digital) -> C
